# Build a Flutter app with Odevio

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      # Launch a build with Odevio
      # You can replace "master" from the link to the tag of the Odevio-CICD repository that you want to use.
      wget -qO- https://raw.githubusercontent.com/Odevio/Odevio-CICD/master/script_cicd.sh | bash /dev/stdin $(ODEVIO_API_KEY) -t ad-hoc

      STATUS=$?
      # If the previous command fails, exit with the same status
      if [ $STATUS -ne 0 ]; then
        echo "Failed to deploy the app to Odevio"
        exit $STATUS
      fi

      # Copy the odevio_ipa_url.txt to the artifact staging directory if it exists
      if [ -f odevio_ipa_url.txt ]; then
        cp odevio_ipa_url.txt $(Build.ArtifactStagingDirectory)
      fi

    failOnStderr: true
    # workingDirectory: "$(System.DefaultWorkingDirectory)/projectFolder/"
    displayName: "deploy-odevio-job"
  - task: PublishBuildArtifacts@1
    displayName: "Publish odevio_ipa_url.txt Artifact"
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "odevio_ipa_url"
